# Generated by Django 4.2.7 on 2024-10-30 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
